name: Windows build and test

on: [push, pull_request]

jobs:
  test:
    name: clang ${{ matrix.clang }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        clang: [17]
        os: [windows-2022]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/boost_1_81_0
        key: ${{runner.os}}-boost

    - name: Cache LLVM-15
      id: cache-llvm15
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/llvm
        key: ${{runner.os}}-llvm${{matrix.clang}}

    - name: Download Ninja
      shell: powershell
      run: |
        $ninjaURL = "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip"
        Invoke-WebRequest $ninjaURL -OutFile ninja.zip
        Expand-Archive -Path ninja.zip -DestinationPath $env:GITHUB_WORKSPACE\ninja_install
        $env:Path += ";$env:GITHUB_WORKSPACE\ninja_install"

    - name: Install MinGW LLVM
      shell: powershell
      run: |
        $llvmURL = "https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-msvcrt-x86_64.zip"
        $llvmFolderName = $llvmUrl.Split("/")[-1].Split(".")[0]
        Invoke-WebRequest $llvmURL -OutFile $env:GITHUB_WORKSPACE\llvm.zip
        Expand-Archive $env:GITHUB_WORKSPACE\llvm.zip
        Move-Item $env:GITHUB_WORKSPACE\llvm\$llvmFolderName\* $env:GITHUB_WORKSPACE\llvm
        Remove-Item $env:GITHUB_WORKSPACE\llvm\$llvmFolderName
        $env:Path = "$env:GITHUB_WORKSPACE\llvm\bin;$env:Path"

    - name: Test LLVM
      shell: powershell
      run: clang++ --version
